#! /bin/sh
#
# Copyright (c) 1997 Silicon Graphics, Inc.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# Install the generic PMDA and/or PMNS
#

. $PCP_DIR/etc/pcp.env
. $PCP_SHARE_DIR/lib/pmdaproc.sh

iam=generic
pmda_interface=2
forced_restart=true

pmdaSetup
pmdaInstall

PMWEBD_LOG_DIR=/mnt/logs/pcp/pmwebd

if [ ! -d "$PMWEBD_LOG_DIR" ]; then
	mkdir $PMWEBD_LOG_DIR
fi

chown pcp $PMWEBD_LOG_DIR

exit 0
